services:
  web:
    networks:
      events_manager:
    container_name: users_ms
    working_dir: /users_ms
    build: .
    volumes:
      - .:/users_ms
    ports:
      - "3002:3002"
    environment:
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3002 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    networks:
      events_manager:
    image: postgres:latest
    container_name: users_ms_db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rails_app_development
networks:
  events_manager:
    name: events_manager
    external: true
