# Use uma imagem base adequada para o Ruby e as dependências do seu aplicativo
FROM ruby:3.2.2-bullseye

# Configurações do ambiente
ENV RAILS_ENV=development

# Crie e configure o diretório de trabalho
WORKDIR /app

# Instale as gemas
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copie o restante do código do aplicativo para o contêiner
COPY . .

# Exemplo de comando de inicialização (você pode precisar ajustar isso)
CMD ["bundle", "exec", "rails", "sneakers:run"]
